apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperway
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hyperway-gateway-api-reader
rules:
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses", "gateways", "httproutes", "referencegrants"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets", "services", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["gateway.networking.k8s.io"]
    resources: ["gatewayclasses/status", "gateways/status", "httproutes/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["hyperway.arloor.dev"]
    resources: ["routesnapshots"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["hyperway.arloor.dev"]
    resources: ["routesnapshots/status"]
    verbs: ["get", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hyperway-gateway-api-reader
subjects:
  - kind: ServiceAccount
    name: hyperway
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hyperway-gateway-api-reader
